[[redirects]]
  from = "/actions.html"
  to = "/#/sign-up?authRequest=:authRequest"
  force = true
  query = {authRequest = ":authRequest"}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "frame-src 'none';"
